### PR TITLE
Registered user can become subscriber and gain access to premium content

### PR DESCRIPTION
**Pull request by rupertlion**
## PT Link

https://www.pivotaltracker.com/story/show/161219085

## PR Includes

* Authenticate articles in view
* Adding subscriptions controller
* Updating routes for subscription controller
* Adding view for new subscription
* Refactoring layouts for namespaces
* Some additional styling for nav bar buttons
* Adding "Get Premium" link for payment

subscriber payment

### CODE REVIEW

**Review by RhonGabriel — APPROVED** [review]

**Comment by tochman** [comment]
I think you should spend a few minutes and aff come tailwind css classes to the form @rupertlion

**Comment by rupertlion** [comment]
Sure - Will that be over-ridden by the stripe form though? (when we implement it)

**Comment by tochman** [comment]
No, no... Don't worry about it.

**Review by oliverochman — APPROVED** [review]
LGTM

**Pull request merged**
